BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB BBBB
    XXXX XXXXXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXX
                  FFFF
                                XXXX XXXXXXXXXX XXXXXXX
                    XXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXXXXXXXXXXFFFFFFFFFFFFXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXXXXXXXXXXFFFFFFFFFFFFXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXX
                                XXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                                XXXX
                                    XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                    XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXX
                                XXXXXXXX
                                XXXXXX XXXXXXXXXXXXX
                                BBB BBBBBB BB BBBBBBB
                                    XXXX
                                        XXX XXXXXXXXXXXXXXXXXX
                                        XXX XXXXXXXXXXXXXX XXXXX
                                        XXX XXXXXXXXXXXXXXXXX
                                    XXXXX

                                BBBBBB


                                XXXXXXXX
                            XXXXXXXX
                        XXXXXX

                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX



    XXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX  XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXX XXX
            XXXXXX

        XXXXXX
    XXXXXXXXX


    XXXXXX
BBBBBBBB