BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBBB BBBB
    XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXX

                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXX XXXX XXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                    XXXX

                        XXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX
                        XXXXX
                        XXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                    XXXXXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBB BBBBB BB BBBBBB
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

                            XXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXXXX XX
                                XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XXXXX
                            XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXFFFFFFFFFFFFXXXXX
                            XXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                X 

                            XXXXX
                            XXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXX
                                        XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                        XXXXXXXXXX
                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXX
                                        XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                        XXXXXXXXXXXXXXXXXXXXXXX XX  XXXXXXXXXXXX XXXXXX  XXXXXXXX X XXXXXXXXX
                                        XXXXXXXXXXXXXXXXXXX
                                        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXX XXXXX XXXXXX X XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                        XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXX XXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                            XXXXX
                            XXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXX
                                XFFFFFFFFFFFFFFFFFFFFFFFXXXXX
                            XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX


                            XXXXXX
                        XXXXX
                        XXXXX

                    BBBBBB


                    XXXXXXXX
                XXXXXXXX
            XXXXXX
        XXXXXX

    XXXXXX
BBBBBBBB