BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBBB BBBB
    XXXX XXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX XX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX BB BBB BBBBBBXXXXXXBBBBBXX
                            XXXXXXXX
                        XXXX
                        BBB BBBBBBBB BB BBBBBBBBBB
                            XX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXX
                               XXXXXXXXXX XXXXXXXXXXX BB BBBBBB BB BBBBBBBBBBBBBXXXXXXXXBBBBBXX
                                
                            XXXX
                        BBBBBB
                    XXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXX
                        BBB BBBBBBB BB BBBBBBBB
                            XXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXX
                                XXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                            XX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBB BBBBBBBBBBBBXXXXXX
                                                    XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
                                        XXXXXX
                                        XXXX XXXXXXXXXXXX
                                            XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                                                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                            XXXXX
                                            XX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
                                                                     XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXX
                                            XXXX
                                            XXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX FFFFFFFFFFFFFFFFFFFFFFF
                                                XXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXX XXXX XXXXXX XXX
                                            XXXXX
                                            XXXXXXX
                                        XXXXXX
                                    XXXXXX


                                    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX

                                        XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
                                           XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                           XXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXX XXXXXXXXXXXXXXX XX XXXXXX
                                            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                                                 XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                                 XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXX XXXX
                                                 XXXXXXXXXXXXXXXXX
                                                XXXXX XXXXXXXXXXXXXXXXXXX
                                                      XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX X XXXXXX X XXXXXXX XXXXXX XXXXXX X XX XXXXXXXXXXXXXXXX X XXXXXX XXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXX XXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXX XXXXX XXXXX XX XX XXXXXXXXXX XXXXX XXXXX XX XX XXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                            XXXXXX
                                            XXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXX XXX
                                        XXXX
                                        XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX BB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXBBBBBX XXXXXXXXX
                                           XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                                           XXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX XXXXX
                                           XXXXXXXXXXXXXXX XX XXXX XXXXXX
                                            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                                                 XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                                                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXX XXXX
                                                 XXXXXXXXXXXXXXXXX
                                                XXXXX XXXXXXXXXXXXXXXXXXX
                                                      XXXXXXXXX XXXXXXXXXX XXXX XXXXX XX XXX XXXX XXXXX XX XXXXX XXXX XXXX XXXXXXXXX XXXXXXXXXX XXXXX XX XXXXXXXXXXX XXXXXXXX XXXX XXXX XXXX XXXX XXXX XXXX X XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXX XXXX XXXX XXXXX XXX XXXXXXXXXXXXXXX
                                            XXXXXX
                                            XXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXX XXX
                                        XXXX

                                    XXXXXX

                                XXXXXX
                            XXXXXX
                        BBBBBB

                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB